handlers:
- url: '/'
  static_files: 'index.html index.htm readme.txt readme.markdown readme.md'
  upload: '.*'
- url: '/'
  static_dir: '/'
- url: '/(.*\.mf)'
  mime_type: 'text/cache-manifest'